"""empty message

Revision ID: 623ae53169e4
Revises: d90488ff9953
Create Date: 2021-02-12 07:51:41.605865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623ae53169e4'
down_revision = 'd90488ff9953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_rooms',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], name='join_rooms_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='join_rooms_user_id_fkey')
    )
    # ### end Alembic commands ###
