"""empty message

Revision ID: 7a3193cd6b9f
Revises: 964a651e028a
Create Date: 2021-02-13 13:20:36.972773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3193cd6b9f'
down_revision = '964a651e028a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
