"""empty message

Revision ID: 964a651e028a
Revises: e4c1baff6e53
Create Date: 2021-02-13 13:19:40.134657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964a651e028a'
down_revision = 'e4c1baff6e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='visitors_pkey')
    )
    # ### end Alembic commands ###
