"""empty message

Revision ID: c49faac15acb
Revises: 623ae53169e4
Create Date: 2021-02-13 06:55:02.467411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49faac15acb'
down_revision = '623ae53169e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_read', sa.Column('room_name', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_read', 'room_name')
    # ### end Alembic commands ###
