"""empty message

Revision ID: d90488ff9953
Revises: e0c5406bb3f5
Create Date: 2021-02-12 02:07:52.286291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90488ff9953'
down_revision = 'e0c5406bb3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_read', sa.Column('last_modified', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_read', 'last_modified')
    # ### end Alembic commands ###
