"""empty message

Revision ID: e4c1baff6e53
Revises: c49faac15acb
Create Date: 2021-02-13 07:20:55.157892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c1baff6e53'
down_revision = 'c49faac15acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_read', sa.Column('room_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_read', 'room_name')
    # ### end Alembic commands ###
